name: Build

on:
  push:
    branches: [ localstack ]
    tags: v*.*
  pull_request:
    branches: [ localstack ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Build
      run: make compile-lambda-linux-all
      
    - uses: actions/upload-artifact@v2
      with:
        name: aws-lambda-rie
        path: bin/*
    - name: Release binaries
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*
        generate_release_notes: true
        prerelease: ${{ endsWith(github.ref, '-pre') }}
